services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: tail -f /dev/null  # 保持容器运行
#     # for neo4j_qa_chain
#     networks:
#       - graph-network

# networks:
#   graph-network:
#     external: true